In [20]:
import numpy as np
import matplotlib.pyplot as plt
import time

In [ ]:
%matplotlib notebook

n_animals = 100
n_steps = 300
speed = 0.05

x = np.ones(n_animals) * 0.5
y = np.ones(n_animals) * 0.5

fig = plt.figure(figsize = (3,3));


for t in range(n_steps):
    x += np.random.randn(n_animals) * speed
    y += np.random.randn(n_animals) * speed
    
    
    #x = np.minimum(x,0)
    #y = np.minimum(y,0)
    #x = np.maximum(x,1)
   # y = np.maximum(y,1)


    
    plt.cla()
    plt.plot(x,y,"k.", markersize = 2)
    fig.canvas.draw()
    time.sleep(0.01)
    plt.xlim((0,1));
    plt.ylim((0,1));
    plt.show()

    x = np.where(x < 0, 0, y)
    y = np.where(y < 0, x, 0)
    x = np.where(x > 1, 0, y)
    y = np.where(y > 1, x, 0)
    
   # for i in range(n_animals):
       # if x[i] < 0:
        #    x[i] = 0
       # elif y[i] < 0:
       #     y[i] = 0
       # elif x[i] > 1:
       #     x[i] = 1
       # elif y[i] > 1:
          #  y[i] = 1
    

the power of numpy is that if we can write a one-liner it will be really fast! so we should try to avoid for loops if possible

for a playground situation, let's create a numpy array with only one negative element and then let's find a way to set this element to 0–so lijmiting from below in our geese-meese situation

In [3]:
a = np.array([1,2,3,-7,4]) # our task is to make this -7 a 0 through limitation
#option #1: slow loop
for i in range(len(a)):
    if a[i] <0: a[i] = 0
print(a)

#option #2, boolean indexing(fast)
a = np.array([1,2,3,-7,4])
print("a<0:" , a<0)
print("a[a<0:", a[a<0]) #logical indexing
a[a<0] = 0 #only set valuesfor those elements where the condition is true
print(a)

#option #3: vectorized formula (fast)
a = np.array([1,2,3,-7,4])
np.maximum(a,0) #np.max calculates the max of all elements, np.maximum applies max to each element
print(a)

[1 2 3 0 4]
a<0: [False False False  True False]
a[a<0: [-7]
[1 2 3 0 4]
[ 1  2  3 -7  4]


In [ ]:
#persistent moose time
%matplotlib notebook

n_animals = 100
n_steps = 100
speed = 0.05

x = np.ones(n_animals) * 0.5
y = np.ones(n_animals) * 0.5

fig = plt.figure(figsize = (3,3));

for a in range(n_animals):
    vx = np.random.rand(n_animals)
    vy = np.random.rand(n_animals)
    
    for t in range(n_steps):
        x += vx * speed
        y += vy * speed
        
        
        plt.cla()
        plt.plot(x,y,"k.", markersize = 2)
        fig.canvas.draw()
        time.sleep(0.01)
        plt.xlim((0,1));
        plt.ylim((0,1));
        plt.show()
        
        x = np.minimum(x,0)
        y = np.minimum(y,0)
        x = np.maximum(x,1)
        y = np.maximum(y,1)